BASIC LOGISTIC REGRESSION MODEL

In [50]:
#import packags, functions and classes
import numpy as np 
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix
import pandas as pd

In [51]:
#step 2
# Get data 

x = np.arange(10).reshape(-1,1)
y = np.array([0,1,0,0,1,1,1,1,1,1])
print(x)
print(y)

[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[0 1 0 0 1 1 1 1 1 1]


In [52]:
#create a model and train it

model = LogisticRegression(solver = 'liblinear', C=10.0, random_state=0)
model.fit(x,y)

LogisticRegression(C=10.0, random_state=0, solver='liblinear')

In [53]:
#evaluate the model 
p_pred = model.predict_log_proba(x)
y_pred = model.predict(x)
score_ = model.score(x,y)
conf_m = confusion_matrix(y,y_pred)
report = classification_report(y,y_pred)

In [54]:
print('x',x,sep = '\n')
print('y',y,sep = '\n', end = '\n\n')

x
[[0]
 [1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
y
[0 1 0 0 1 1 1 1 1 1]



In [55]:
#intercept
print('intercept:', model.intercept_)
print('coef:', model.coef_, end='\n\n')

intercept: [-1.51632619]
coef: [[0.703457]]



In [56]:
print('y_actual:', y)
print('y_pred:',y_pred)

y_actual: [0 1 0 0 1 1 1 1 1 1]
y_pred: [0 0 0 1 1 1 1 1 1 1]


In [57]:
#confusion matrix
print('conf_m:', conf_m, sep='\n', end='\n\n')

conf_m:
[[2 1]
 [1 6]]



In [58]:
print('report:', report, sep = '\n')

report:
              precision    recall  f1-score   support

           0       0.67      0.67      0.67         3
           1       0.86      0.86      0.86         7

    accuracy                           0.80        10
   macro avg       0.76      0.76      0.76        10
weighted avg       0.80      0.80      0.80        10



In [59]:
# test_locations.nunique()

In [60]:
# orders.head()
#orders.shape

In [61]:
# test_customers.head()
#test_customers.shape

In [62]:
# train_customers.head()
#train_customers.shape

In [63]:
# train_locations.head()
#train_locations.shape

In [64]:
# vendors.head()
#vendors.shape

In [65]:
# test_customers.isnull().sum()

In [66]:
# vendors.head()

In [67]:
# vendors.isnull().sum()

In [68]:
# train_locations

In [69]:
# SampleSubmission.isnull().sum()

In [70]:
orders = pd.read_csv('/Users/da_m1_52/Downloads/orders.csv')
vendors = pd.read_csv('/Users/da_m1_52/Downloads/vendors.csv')
SampleSubmission = pd.read_csv('/Users/da_m1_52/Downloads/SampleSubmission.csv')

/var/folders/5g/55_x_kdn3fx9kqydvjsl9qwr0000gn/T/ipykernel_20594/405158135.py:1: DtypeWarning: Columns (15,16,18,19,20) have mixed types. Specify dtype option on import or set low_memory=False.
  orders = pd.read_csv('/Users/da_m1_52/Downloads/orders.csv')


In [71]:
train_customers

akeed_customer_id gender  dob  status  verified language  \
0               TCHWPBT   Male  NaN       1         1       EN   
1               ZGFSYCZ   Male  NaN       1         1       EN   
2               S2ALZFL   Male  NaN       0         1       EN   
3               952DBJQ   Male  NaN       1         1       EN   
4               1IX6FXS   Male  NaN       1         1       EN   
...                 ...    ...  ...     ...       ...      ...   
34669           JAI79PE    NaN  NaN       1         1      NaN   
34670           TR75VFL    NaN  NaN       1         1      NaN   
34671           SQMJ08H    NaN  NaN       1         1      NaN   
34672           9LW9CHN    NaN  NaN       1         1      NaN   
34673           LBMRK7A    NaN  NaN       1         1      NaN   

                created_at           updated_at  
0      2018-02-07 19:16:23  2018-02-07 19:16:23  
1      2018-02-09 12:04:42  2018-02-09 12:04:41  
2      2018-03-14 18:31:43  2018-03-14 18:31:42  
3      2018-03-15 19:47:07  2018-03-15 19:47:07  
4      2018-03-15 19:57:01  2018-03-15 19:57:01  
...                    ...                  ...  
34669  2020-03-03 13:01:13  2020-03-03 13:02:21  
34670  2020-03-03 13:22:35  2020-03-03 13:22:41  
34671  2020-03-03 13:24:27  2020-03-03 13:24:44  
34672  2020-03-03 13:24:28  2020-03-03 13:28:00  
34673  2020-03-03 13:31:52  2020-03-03 13:32:09  

[34674 rows x 8 columns]

In [72]:
SampleSubmission

CID X LOC_NUM X VENDOR  target
0            Z59FTQD X 0 X 243       0
1            0JP29SK X 0 X 243       0
2            0JP29SK X 1 X 243       0
3            0JP29SK X 2 X 243       0
4            0JP29SK X 3 X 243       0
...                        ...     ...
1671995      L9G4OFV X 4 X 907       0
1671996      L9G4OFV X 5 X 907       0
1671997      FDZFYBA X 0 X 907       0
1671998      UTKHR1C X 0 X 907       0
1671999      3O8LSR3 X 0 X 907       0

[1672000 rows x 2 columns]

TRAIN DATA

In [73]:
train_customers = pd.read_csv('/Users/da_m1_52/Downloads/train_customers.csv')
train_locations = pd.read_csv('/Users/da_m1_52/Downloads/train_locations.csv')

In [74]:
train_customers.duplicated().sum()

0

In [75]:
train_locations.duplicated().sum()

0

In [76]:
train_customers.head(15)
#train_customers.shape

akeed_customer_id  gender     dob  status  verified language  \
0            TCHWPBT    Male     NaN       1         1       EN   
1            ZGFSYCZ    Male     NaN       1         1       EN   
2            S2ALZFL    Male     NaN       0         1       EN   
3            952DBJQ    Male     NaN       1         1       EN   
4            1IX6FXS    Male     NaN       1         1       EN   
5            IL9MJSW    Male     NaN       1         1       EN   
6            EZTXK46    Male  1957.0       1         1       EN   
7            A79YCES    Male     NaN       1         1       EN   
8            Y39V6UD    Male     NaN       1         1       EN   
9            XRPTQNV    Male     NaN       1         1       EN   
10           8OSXJI8    Male     NaN       1         1       EN   
11           FYTKIIM    Male     NaN       1         1       EN   
12           FJ8AF4X    Male     NaN       1         1       EN   
13           E1L5EUE    Male     NaN       1         1       EN   
14           9VJZUWB  Female  1970.0       1         1       EN   

             created_at           updated_at  
0   2018-02-07 19:16:23  2018-02-07 19:16:23  
1   2018-02-09 12:04:42  2018-02-09 12:04:41  
2   2018-03-14 18:31:43  2018-03-14 18:31:42  
3   2018-03-15 19:47:07  2018-03-15 19:47:07  
4   2018-03-15 19:57:01  2018-03-15 19:57:01  
5   2018-03-16 18:22:00  2018-03-16 18:22:00  
6   2018-03-16 21:46:19  2020-03-21 21:01:33  
7   2018-03-22 16:48:06  2018-03-22 16:48:06  
8   2018-03-22 19:55:54  2018-03-22 19:55:53  
9   2018-03-25 11:36:30  2018-03-25 11:36:30  
10  2018-03-30 22:28:12  2018-03-30 22:28:11  
11  2018-04-25 16:39:46  2018-04-25 16:39:46  
12  2018-04-25 16:39:52  2018-04-25 16:39:51  
13  2018-04-25 18:39:04  2018-04-25 18:39:04  
14  2018-04-30 00:57:51  2019-11-23 18:34:48

In [77]:
train_locations.head()
#train_locations.shape

customer_id  location_number location_type  latitude  longitude
0     02SFNJH                0           NaN  1.682392 -78.789737
1     02SFNJH                1           NaN  1.679137   0.766823
2     02SFNJH                2           NaN -0.498648   0.661241
3     RU43CXC                0          Home  0.100853   0.438165
4     BDFBPRD                0           NaN  2.523125   0.733464

In [78]:
train_customers .isnull().sum()
#train_customers.dropna()
current_year = pd.to_datetime('today').year
train_customers ['dob'] = current_year - train_customers ['dob']


In [79]:
train_locations.isnull().sum()

customer_id            0
location_number        0
location_type      27209
latitude               6
longitude              6
dtype: int64

In [80]:
train_locations['location_type'].fillna(train_locations['location_type'].mode()[0], inplace=True)
train_locations['latitude'].fillna(train_locations['latitude'].mean(), inplace=True)
train_locations['longitude'].fillna(train_locations['longitude'].mean(), inplace=True)

In [81]:
train_locations.isnull().sum()

customer_id        0
location_number    0
location_type      0
latitude           0
longitude          0
dtype: int64

In [82]:
train_customers ['gender'].fillna(train_customers ['gender'].mode()[0], inplace=True)
train_customers ['language'].fillna(train_customers ['language'].mode()[0], inplace=True)
#Statistical Distribution

# mean_dob = train_customers['dob'].mean()
# std_dob = train_customers['dob'].std()
# missing_dob_count = train_customers['dob'].isnull().sum()

# imputed_dob_values = np.random.normal(mean_dob, std_dob, missing_dob_count)
# train_customers.loc[train_customers['dob'].isnull(), 'dob'] = imputed_dob_values


In [83]:
missing_perc = train_customers .isna().sum()/train_customers .shape[0]*100
missing_perc

akeed_customer_id     0.00000
gender                0.00000
dob                  91.21532
status                0.00000
verified              0.00000
language              0.00000
created_at            0.00000
updated_at            0.00000
dtype: float64

In [84]:
train_customers 



akeed_customer_id gender  dob  status  verified language  \
0               TCHWPBT   Male  NaN       1         1       EN   
1               ZGFSYCZ   Male  NaN       1         1       EN   
2               S2ALZFL   Male  NaN       0         1       EN   
3               952DBJQ   Male  NaN       1         1       EN   
4               1IX6FXS   Male  NaN       1         1       EN   
...                 ...    ...  ...     ...       ...      ...   
34669           JAI79PE   Male  NaN       1         1       EN   
34670           TR75VFL   Male  NaN       1         1       EN   
34671           SQMJ08H   Male  NaN       1         1       EN   
34672           9LW9CHN   Male  NaN       1         1       EN   
34673           LBMRK7A   Male  NaN       1         1       EN   

                created_at           updated_at  
0      2018-02-07 19:16:23  2018-02-07 19:16:23  
1      2018-02-09 12:04:42  2018-02-09 12:04:41  
2      2018-03-14 18:31:43  2018-03-14 18:31:42  
3      2018-03-15 19:47:07  2018-03-15 19:47:07  
4      2018-03-15 19:57:01  2018-03-15 19:57:01  
...                    ...                  ...  
34669  2020-03-03 13:01:13  2020-03-03 13:02:21  
34670  2020-03-03 13:22:35  2020-03-03 13:22:41  
34671  2020-03-03 13:24:27  2020-03-03 13:24:44  
34672  2020-03-03 13:24:28  2020-03-03 13:28:00  
34673  2020-03-03 13:31:52  2020-03-03 13:32:09  

[34674 rows x 8 columns]

TEST DATA

In [85]:
test_locations = pd.read_csv('/Users/da_m1_52/Downloads/test_locations.csv')
test_customers = pd.read_csv('/Users/da_m1_52/Downloads/test_customers.csv')


In [86]:
test_locations.head()
#test_locations.shape

customer_id  location_number location_type    latitude  longitude
0     Z59FTQD                0           NaN  126.032278  -9.106019
1     0JP29SK                0          Home    0.278709 -78.623847
2     0JP29SK                1          Home    0.124485 -78.605621
3     0JP29SK                2           NaN   -0.113891 -78.577449
4     0JP29SK                3           NaN   -0.848796   0.136726

In [87]:
test_customers.head()
#test_customers.shape

akeed_customer_id gender     dob  status  verified language  \
0           ICE2DJP   Male     NaN       1         1       EN   
1           FWNUI71   Male     NaN       1         1       EN   
2           LRX7BCH   Male     NaN       1         1       EN   
3           D96DHMD   Male     NaN       1         1       EN   
4           88Q8Y5V   Male  1997.0       1         1       EN   

            created_at           updated_at  
0  2018-02-07 16:45:36  2018-02-07 16:45:36  
1  2018-03-22 20:11:47  2018-03-22 20:11:47  
2  2018-04-17 20:01:15  2018-04-17 20:01:15  
3  2018-04-29 22:35:52  2018-04-29 22:35:52  
4  2018-05-05 12:38:09  2018-05-05 12:38:09

In [88]:
train_customers .head()

akeed_customer_id gender  dob  status  verified language  \
0           TCHWPBT   Male  NaN       1         1       EN   
1           ZGFSYCZ   Male  NaN       1         1       EN   
2           S2ALZFL   Male  NaN       0         1       EN   
3           952DBJQ   Male  NaN       1         1       EN   
4           1IX6FXS   Male  NaN       1         1       EN   

            created_at           updated_at  
0  2018-02-07 19:16:23  2018-02-07 19:16:23  
1  2018-02-09 12:04:42  2018-02-09 12:04:41  
2  2018-03-14 18:31:43  2018-03-14 18:31:42  
3  2018-03-15 19:47:07  2018-03-15 19:47:07  
4  2018-03-15 19:57:01  2018-03-15 19:57:01

In [89]:
summary1 = test_customers.describe()
summary2 = train_customers .describe()

# Compare summary statistics
summary_comparison = summary1 == summary2
summary_comparison

dob  status  verified
count  False   False     False
mean   False   False     False
std    False   False     False
min    False    True      True
25%    False    True      True
50%    False    True      True
75%    False    True      True
max    False    True      True

In [90]:
train_customers .shape

(34674, 8)

In [91]:
test_locations.isnull().sum()

customer_id           0
location_number       0
location_type      7650
latitude              3
longitude             3
dtype: int64

In [92]:
test_locations['location_type'].fillna(test_locations['location_type'].mode()[0], inplace=True)
test_locations['latitude'].fillna(test_locations['latitude'].mean(), inplace=True)
test_locations['longitude'].fillna(test_locations['longitude'].mean(), inplace=True)



In [93]:
vendors.dropna(inplace=True)


In [94]:
orders

akeed_order_id customer_id  item_count  grand_total  payment_mode  \
0             163238.0     92PEE24         1.0          7.6             2   
1             163240.0     QS68UD8         1.0          8.7             1   
2             163241.0     MB7VY5F         2.0         14.4             1   
3             163244.0     KDJ951Y         1.0          7.1             1   
4             163245.0     BAL0RVT         4.0         27.2             1   
...                ...         ...         ...          ...           ...   
135298        415507.0     L6LFY6H         1.0         13.3             2   
135299        415508.0     2GMMVGI         3.0          9.5             1   
135300        415510.0     LYTAAV0         4.0         18.2             2   
135301        415512.0     NEV9A5D         3.0          7.7             1   
135302        415515.0     77KCRC1         1.0          6.8             2   

       promo_code  vendor_discount_amount  promo_code_discount_percentage  \
0             NaN                     0.0                             NaN   
1             NaN                     0.0                             NaN   
2             NaN                     0.0                             NaN   
3             NaN                     0.0                             NaN   
4             NaN                     0.0                             NaN   
...           ...                     ...                             ...   
135298        NaN                     0.0                             0.0   
135299        NaN                     0.0                             0.0   
135300        NaN                     0.0                             0.0   
135301  NUE5BZAA7                     0.0                             0.0   
135302        NaN                     0.0                             0.0   

       is_favorite is_rated  ...  driver_accepted_time  ready_for_pickup_time  \
0              NaN       No  ...                   NaN                    NaN   
1              NaN       No  ...                   NaN                    NaN   
2              NaN       No  ...                   NaN                    NaN   
3              NaN       No  ...                   NaN                    NaN   
4              NaN       No  ...                   NaN                    NaN   
...            ...      ...  ...                   ...                    ...   
135298          No       No  ...   2020-02-29 23:59:21    2020-03-01 00:02:10   
135299          No      Yes  ...   2020-03-01 00:19:46    2020-03-01 00:20:05   
135300          No       No  ...   2020-03-01 00:04:28    2020-03-01 00:10:34   
135301          No       No  ...   2020-03-01 00:06:14    2020-03-01 00:08:10   
135302          No       No  ...   2020-03-01 00:07:21    2020-03-01 00:14:12   

             picked_up_time       delivered_time        delivery_date  \
0                       NaN                  NaN  2019-07-31 05:30:00   
1                       NaN                  NaN  2019-07-31 05:30:00   
2                       NaN                  NaN  2019-07-31 05:30:00   
3                       NaN                  NaN  2019-07-31 05:30:00   
4                       NaN                  NaN  2019-07-31 05:30:00   
...                     ...                  ...                  ...   
135298  2020-03-01 00:22:53  2020-03-01 00:29:42                  NaN   
135299  2020-03-01 00:27:50  2020-03-01 01:03:14                  NaN   
135300  2020-03-01 00:14:43  2020-03-01 00:36:37                  NaN   
135301  2020-03-01 00:22:11  2020-03-01 00:36:52                  NaN   
135302  2020-03-01 00:21:33  2020-03-01 00:28:06                  NaN   

       vendor_id           created_at LOCATION_NUMBER LOCATION_TYPE  \
0            105  2019-08-01 05:30:16               0           NaN   
1            294  2019-08-01 05:31:10               0          Work   
2             83  2019-08-01 05:31:33               0           NaN   
3             90  2019-0

In [95]:
#akeed_order_id
mode_promo_code = orders['akeed_order_id'].mode()[0]
orders['akeed_order_id'].fillna(mode_promo_code, inplace=True)

#item_count
mean_dob = orders['item_count'].mean()
orders['item_count'].fillna(mean_dob, inplace=True)

#promo_code
mode_promo_code = orders['promo_code'].mode()[0]
orders['promo_code'].fillna(mode_promo_code, inplace=True)

#promo_code_discount_percentage
mean_discount_percentage = orders['promo_code_discount_percentage'].mean()
orders['promo_code_discount_percentage'].fillna(mean_discount_percentage, inplace=True)

#is_favorite
mode_is_favorite = orders['is_favorite'].mode()[0]
orders['is_favorite'].fillna(mode_is_favorite, inplace=True)

#vendor_rating
mean_rating = orders['vendor_rating'].mean()
orders['vendor_rating'].fillna(mean_rating, inplace=True)

#ready_for_pickup_time
mode_accepted_time = orders['ready_for_pickup_time'].mode()[0]
orders['ready_for_pickup_time'].fillna(mode_accepted_time, inplace=True)

#picked_up_time
mode_accepted_time = orders['picked_up_time'].mode()[0]
orders['picked_up_time'].fillna(mode_accepted_time, inplace=True)

#delivered_time
mode_accepted_time = orders['delivered_time'].mode()[0]
orders['delivered_time'].fillna(mode_accepted_time, inplace=True)

#delivery_date
mode_accepted_time = orders['delivery_date'].mode()[0]
orders['delivery_date'].fillna(mode_accepted_time, inplace=True)

#driver_accepted_time
mode_accepted_time = orders['driver_accepted_time'].mode()[0]
orders['driver_accepted_time'].fillna(mode_accepted_time, inplace=True)

#preparationtime
mode_accepted_time = orders['preparationtime'].mode()[0]
orders['preparationtime'].fillna(mode_accepted_time, inplace=True)

#delivery_time
mode_accepted_time = orders['delivery_time'].mode()[0]
orders['delivery_time'].fillna(mode_accepted_time, inplace=True)

#order_accepted_time
mode_accepted_time = orders['order_accepted_time'].mode()[0]
orders['order_accepted_time'].fillna(mode_accepted_time, inplace=True)

#location_type
mode_location_type = orders['LOCATION_TYPE'].mode()[0]
orders['LOCATION_TYPE'].fillna(mode_location_type, inplace=True)




In [96]:
orders.isnull().sum()

akeed_order_id                    0
customer_id                       0
item_count                        0
grand_total                       0
payment_mode                      0
promo_code                        0
vendor_discount_amount            0
promo_code_discount_percentage    0
is_favorite                       0
is_rated                          0
vendor_rating                     0
driver_rating                     0
deliverydistance                  0
preparationtime                   0
delivery_time                     0
order_accepted_time               0
driver_accepted_time              0
ready_for_pickup_time             0
picked_up_time                    0
delivered_time                    0
delivery_date                     0
vendor_id                         0
created_at                        0
LOCATION_NUMBER                   0
LOCATION_TYPE                     0
CID X LOC_NUM X VENDOR            0
dtype: int64

In [97]:
# median_dob = train_customers['dob'].median()
# train_customers['dob'].fillna(median_dob, inplace=True)


In [98]:
test_customers['gender'].fillna(test_customers['gender'].mode()[0], inplace=True)
test_customers['language'].fillna(test_customers['language'].mode()[0], inplace=True)


# mean_dob = test_customers['dob'].mean()
# std_dob = test_customers['dob'].std()
# missing_dob_count = test_customers['dob'].isnull().sum()

# imputed_dob_values = np.random.normal(mean_dob, std_dob, missing_dob_count)
# test_customers.loc[test_customers['dob'].isnull(), 'dob'] = imputed_dob_values

In [99]:
# Concatenate the matrices vertically
combined_matrix = pd.concat([test_locations, orders, test_customers, train_customers , train_locations, vendors, SampleSubmission], axis=0)

# Calculate the correlation matrix
correlation_matrix = combined_matrix.corr()

# Display the correlation matrix
print(correlation_matrix)


/var/folders/5g/55_x_kdn3fx9kqydvjsl9qwr0000gn/T/ipykernel_20594/2641544624.py:5: FutureWarning: The default value of numeric_only in DataFrame.corr is deprecated. In a future version, it will default to False. Select only valid columns or specify the value of numeric_only to silence this warning.
  correlation_matrix = combined_matrix.corr()


                                location_number  latitude  longitude  \
location_number                        1.000000 -0.030379   0.245602   
latitude                              -0.030379  1.000000   0.076806   
longitude                              0.245602  0.076806   1.000000   
akeed_order_id                              NaN       NaN        NaN   
item_count                                  NaN       NaN        NaN   
grand_total                                 NaN       NaN        NaN   
payment_mode                                NaN       NaN        NaN   
vendor_discount_amount                      NaN       NaN        NaN   
promo_code_discount_percentage              NaN       NaN        NaN   
vendor_rating                               NaN -0.033045   0.441444   
driver_rating                               NaN       NaN        NaN   
deliverydistance                            NaN       NaN        NaN   
preparationtime                             NaN       NaN       

In [100]:
train_customers 

akeed_customer_id gender  dob  status  verified language  \
0               TCHWPBT   Male  NaN       1         1       EN   
1               ZGFSYCZ   Male  NaN       1         1       EN   
2               S2ALZFL   Male  NaN       0         1       EN   
3               952DBJQ   Male  NaN       1         1       EN   
4               1IX6FXS   Male  NaN       1         1       EN   
...                 ...    ...  ...     ...       ...      ...   
34669           JAI79PE   Male  NaN       1         1       EN   
34670           TR75VFL   Male  NaN       1         1       EN   
34671           SQMJ08H   Male  NaN       1         1       EN   
34672           9LW9CHN   Male  NaN       1         1       EN   
34673           LBMRK7A   Male  NaN       1         1       EN   

                created_at           updated_at  
0      2018-02-07 19:16:23  2018-02-07 19:16:23  
1      2018-02-09 12:04:42  2018-02-09 12:04:41  
2      2018-03-14 18:31:43  2018-03-14 18:31:42  
3      2018-03-15 19:47:07  2018-03-15 19:47:07  
4      2018-03-15 19:57:01  2018-03-15 19:57:01  
...                    ...                  ...  
34669  2020-03-03 13:01:13  2020-03-03 13:02:21  
34670  2020-03-03 13:22:35  2020-03-03 13:22:41  
34671  2020-03-03 13:24:27  2020-03-03 13:24:44  
34672  2020-03-03 13:24:28  2020-03-03 13:28:00  
34673  2020-03-03 13:31:52  2020-03-03 13:32:09  

[34674 rows x 8 columns]